=== m-amaris/PIAT-JavaCC/[02] PIAT/Laboratorio/Practica 3/Ejemplos SAX/SAX_Example_1/src/libreria.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
			targetNamespace="http://www.example.org/libreria" 
			xmlns:tns="http://www.example.org/libreria" 
			elementFormDefault="qualified">

<xsd:element name="libro">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element name="titulo" type="xsd:string"/>
            <xsd:element name="autor" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:element>

<xsd:element name="libreria" >
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element ref="tns:libro" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
</xsd:element>
			

</xsd:schema>

=== m-amaris/PIAT-JavaCC/[02] PIAT/Laboratorio/Practica 3/Ejemplos SAX/SAX_Example_1/src/libreria.xml
<?xml version="1.0" encoding="UTF-8"?>
<lib:libreria 
		xmlns:lib="http://www.example.org/libreria" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://www.example.org/libreria ./libreria.xsd">
     <lib:libro>
        <lib:titulo>El Asedio</lib:titulo>
        <lib:autor>Arturo Pérez Reverte</lib:autor>
    </lib:libro>
    <lib:libro>
        <lib:titulo>El viaje de Baldassare</lib:titulo>
        <lib:autor>Amin Maalouf</lib:autor>
    </lib:libro>
    <lib:libro>
        <lib:titulo>La sombre del ciprés es alargada</lib:titulo>
        <lib:autor>Miguel Delibes</lib:autor>
    </lib:libro>
</lib:libreria>
