=== m-amaris/PIAT-JavaCC/[02] PIAT/Laboratorio/Practica 1/fase3/modulo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- MODULO-MIGUEL-AMARÍS -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.piat.upm.es/modulo" 
xmlns:tns="http://www.piat.upm.es/modulo" 
elementFormDefault="qualified">
    
    <xsd:element name="modulo" type="tns:tipoModulo" />

    <xsd:complexType name="tipoModulo">
        <xsd:sequence>
            <xsd:element name="tipoModulo" type="tns:tipoTipoModulo" minOccurs="1" maxOccurs="1" />
            <xsd:element name="funcionalidad" type="tns:tipoFuncionalidad" minOccurs="1" maxOccurs="1" />
            <xsd:element name="componentes" type="tns:tipoComponentes" />
        </xsd:sequence>
        <xsd:attribute name="idModulo" type="tns:tipoIdModulo" use="required" />
    </xsd:complexType>

    <xsd:simpleType name="tipoIdModulo">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Z]{3}[e,t][0-9]{4}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="tipoTipoModulo">
        <xsd:restriction base="xsd:token">
            <xsd:enumeration value="específico" />
            <xsd:enumeration value="transmisor" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="tipoFuncionalidad">
        <xsd:restriction base="xsd:string">
            <xsd:maxLength value="512" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="tipoComponentes">
            <xsd:choice>
                <xsd:element name="transmisores" type="tns:tipoTransmisores">
                    <xsd:key name="transmisorKey">
                        <xsd:selector xpath=".//tns:transmisor" />
                        <xsd:field xpath="@idTransmisor" />
                    </xsd:key>
                </xsd:element>
                <xsd:element name="captadores" type="tns:tipoCaptadores">
                    <xsd:key name="captadorKey">
                        <xsd:selector xpath=".//tns:captador" />
                        <xsd:field xpath="@idCaptador" />
                    </xsd:key>
                </xsd:element>
            </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="tipoCaptadores">
        <xsd:sequence>
            <xsd:element name="numeroCaptadores" type="xsd:int" minOccurs="1" />
            <xsd:sequence>
                <xsd:element name="captador" type="tns:tipoCaptador" minOccurs="1" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tipoCaptador">
        <xsd:sequence>
            <xsd:element name="parametro" type="tns:tipoParametro"  />
            <xsd:element name="medida" type="tns:tipoMedida" minOccurs="0" />
        </xsd:sequence>
        <xsd:attribute name="idCaptador" type="tns:tipoIdCaptador" use="required" />
    </xsd:complexType>

    <xsd:simpleType name="tipoIdCaptador">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Z][a-z]{2}[0-9]{3}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="tipoParametro">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="5" />
            <xsd:maxLength value="25" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="tipoMedida">
        <xsd:sequence>
            <xsd:element name="valor" type="xsd:int" />
            <xsd:element name="unidades" type="xsd:string" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tipoTransmisores">
        <xsd:sequence>
            <xsd:element name="numeroTransmisores" type="xsd:int" />
            <xsd:sequence>
                <xsd:element name="transmisor" type="tns:tipoTransmisor" minOccurs="1" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tipoTransmisor">
        <xsd:sequence>
            <xsd:element name="parametrosTransmision" type="tns:tipoParametrosTransmision" />
        </xsd:sequence>
        <xsd:attribute name="idTransmisor" type="tns:tipoIdTransmisor" use="required" />
    </xsd:complexType>

    <xsd:simpleType name="tipoIdTransmisor">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="TR[0-9][a-z]{3}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="tipoParametrosTransmision">
        <xsd:sequence>
            <xsd:element name="tipoModulacion" type="tns:tipoTipoModulacion"  />
            <xsd:element name="tiempoVida" type="tns:tipoTiempoVida" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="tipoTipoModulacion">
        <xsd:restriction base="xsd:token">
            <xsd:enumeration value="BPSK" />
            <xsd:enumeration value="QPSK" />
            <xsd:enumeration value="16QAM" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="tipoTiempoVida">
        <xsd:restriction base="tns:tipoListaFechas">
            <xsd:minLength value="1"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="tipoListaFechas">
        <xsd:list itemType="xsd:date"/>
    </xsd:simpleType>
</xsd:schema>

=== m-amaris/PIAT-JavaCC/[02] PIAT/Laboratorio/Practica 1/fase2/moduloTransmisores.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- MODULO-MIGUEL-AMARÍS -->
<mod:modulo xmlns:mod="http://www.piat.upm.es/modulo" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.piat.upm.es/modulo modulo.xsd" 
idModulo="MODt0001">

    <mod:tipoModulo>transmisor</mod:tipoModulo>
    <mod:funcionalidad></mod:funcionalidad>
    <mod:componentes>
        <mod:transmisores>
            <mod:numeroTransmisores>2</mod:numeroTransmisores>
            <mod:transmisor idTransmisor="TR1mfm">
                <mod:parametrosTransmision>
                    <mod:tipoModulacion>BPSK</mod:tipoModulacion>
                    <mod:tiempoVida>
                        2022-01-27
                       2022-01-29
                    </mod:tiempoVida>
                </mod:parametrosTransmision>
            </mod:transmisor>
            <mod:transmisor idTransmisor="TR1mfn">
                <mod:parametrosTransmision>
                    <mod:tipoModulacion>BPSK</mod:tipoModulacion>
                    <mod:tiempoVida>
                       2001-01-12
                       2001-12-12
                    </mod:tiempoVida>
                </mod:parametrosTransmision>
            </mod:transmisor>
        </mod:transmisores>
    </mod:componentes>
</mod:modulo>

=== m-amaris/PIAT-JavaCC/[02] PIAT/Laboratorio/Practica 1/fase2/moduloCaptadores.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--MODULO-MIGUEL-AMARÍS -->
<mod:modulo xmlns:mod="http://www.piat.upm.es/modulo" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.piat.upm.es/modulo modulo.xsd" 
idModulo="MODt0001">

    <mod:tipoModulo>específico</mod:tipoModulo>
    <mod:funcionalidad>
        Este modulo se encarga de analizar parametros de la capa de ozono, como su
		nivel de ozono y temperatura 
    </mod:funcionalidad>
    <mod:componentes>
        <mod:captadores>
            <mod:numeroCaptadores>2</mod:numeroCaptadores>
            <mod:captador idCaptador="Cap001">
                <mod:parametro>nivel de ozono</mod:parametro>
                <mod:medida>
                    <mod:valor>45 </mod:valor>
                    <mod:unidades>µg/m3</mod:unidades>
                </mod:medida>
            </mod:captador>
            <mod:captador idCaptador="Cap002">
                <mod:parametro>temperatura</mod:parametro>
            </mod:captador>
        </mod:captadores>
    </mod:componentes>
</mod:modulo>
