=== m-amaris/PIAT-JavaCC/[02] PIAT/documentos PIAT/LAB PIAT/P1/fase2/sistemaTransformacion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.piat.upm.es/sistemaTransformacion"
 xmlns:tns="http://www.piat.upm.es/sistemaTransformacion"
 xmlns:mod="http://www.piat.upm.es/modulo"
 elementFormDefault="qualified">

<xsd:import namespace="http://www.piat.upm.es/modulo" schemaLocation="./modulo.xsd"/>


<xsd:element name="sistemaTF" type="tns:tipoSistemaTF"/>

<xsd:complexType name="tipoSistemaTF">
    <xsd:sequence>
        <xsd:element name="informacionEntrada" type="tns:tInfoEntrada"/>
        <xsd:element name="informacionSalida" type="tns:tInfoSalida"/>
    </xsd:sequence>
    <xsd:attribute name="idSistemaTF" type="tns:tIdSistemaTF" use="required"/>
</xsd:complexType>

<xsd:simpleType name="tIdSistemaTF">
    <xsd:restriction base="xsd:token">
        <xsd:pattern value="TF[0-9]{3}"/>
    </xsd:restriction>
</xsd:simpleType>

<xsd:complexType name="tInfoEntrada">
    <xsd:choice>
        <xsd:element name="valor" type="tns:tValor"/>
        <xsd:element name="foto" type="tns:tFoto"/>
    </xsd:choice>
</xsd:complexType>

<xsd:complexType name="tValor">
    <xsd:sequence>
        <xsd:element name="parametro" type="mod:tParametro"/>
        <xsd:element name="medida" type="mod:tMedida"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="tFoto">
    <xsd:all>
        <xsd:element name="distancia" type="xsd:decimal"/>
        <xsd:element name="centro" type="tns:tCentro"/>
        <xsd:element name="forma" type="tns:tForma"/>
    </xsd:all>
</xsd:complexType>

<xsd:complexType name="tCentro">
    <xsd:sequence>
        <xsd:element name="longitud" type="tns:tLongitud"/>
        <xsd:element name="latitud" type="tns:tLatitud"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:simpleType name="tLongitud">
    <xsd:restriction base="xsd:decimal">
        <xsd:maxInclusive value="180"/>
        <xsd:minInclusive value="0"/>
    </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="tLatitud">
    <xsd:restriction base="xsd:decimal">
        <xsd:maxInclusive value="90"/>
        <xsd:minInclusive value="-90"/>
    </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="tForma">
    <xsd:restriction base="xsd:token">
        <xsd:enumeration value="cuadrado"/>
        <xsd:enumeration value="rectÃ¡ngulo"/>
    </xsd:restriction>
</xsd:simpleType>

<xsd:complexType name="tInfoSalida">
    <xsd:choice>
        <xsd:element name="texto" type="tns:tTexto"/>
        <xsd:element name="imagen" type="tns:tImagen"/>
    </xsd:choice>
</xsd:complexType>

<xsd:complexType name="tTexto">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
          <xsd:attribute name="formato" type="xsd:token"/>
          <xsd:attribute name="lomgitud" type="xsd:nonNegativeInteger"/>
      </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="tImagen">
    <xsd:all>
        <xsd:element name="dimensiones" type="tns:tDimensiones"/>
        <xsd:element name="descripcion" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="contenido" type="tns:tContenido"/>
    </xsd:all>
    <xsd:attribute name="idImagen" type="tns:tIdImagen" use="required"/>
</xsd:complexType>

<xsd:simpleType name="tIdImagen">
    <xsd:restriction base="xsd:token">
        <xsd:pattern value="IMAG[0-9]{3}"/>
    </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="ListaEnteros">
    <xsd:list itemType="xsd:integer"/>
</xsd:simpleType>

<xsd:simpleType name="tDimensiones">
    <xsd:restriction base="tns:ListaEnteros">
        <xsd:length value="2"/>
    </xsd:restriction>
</xsd:simpleType>

<xsd:complexType name="tContenido">
    <xsd:simpleContent>
        <xsd:extension base="xsd:base64Binary">
            <xsd:attribute name="formato" type="tns:tFormatoImg" use="required"/>
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>

<xsd:simpleType name="tFormatoImg">
    <xsd:restriction base="xsd:token">
        <xsd:enumeration value="GIF"/>
        <xsd:enumeration value="JPEG"/>
        <xsd:enumeration value="PNG"/>
    </xsd:restriction>
</xsd:simpleType>

<xsd:notation name="GIF" public="image/gif" system="paint.exe"/>
<xsd:notation name="JPEG" public="image/jpeg" system="paint.exe"/>
<xsd:notation name="PNG" public="image/png" system="paint.exe"/>

</xsd:schema>

=== m-amaris/PIAT-JavaCC/[02] PIAT/documentos PIAT/LAB PIAT/P1/fase2/sistemaTransformacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<stf:sistemaTF idSistemaTF="TF001" 
xmlns:stf="http://www.piat.upm.es/sistemaTransformacion" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.piat.upm.es/sistemaTransformacion sistemaTransformacion.xsd">
    <stf:informacionEntrada>
        <stf:foto>
            <stf:distancia>637</stf:distancia>
            <stf:centro>
                <stf:longitud>118</stf:longitud>
                <stf:latitud>-47</stf:latitud>
            </stf:centro>
            <stf:forma>cuadrado</stf:forma>
        </stf:foto>
    </stf:informacionEntrada>
    <stf:informacionSalida>
        <stf:imagen idImagen="IMAG001">
            <stf:dimensiones>
                286 873
            </stf:dimensiones>
            <stf:descripcion>
                esto es una descripcion
            </stf:descripcion>
            <stf:contenido formato="GIF">
                iVBORw0KGgoAAAANSUhEUgAABPQAAAKYCAIAAAB7PTEjAAAAAXNSR0IArs4c6QAAAARnQU1BAACx
            </stf:contenido>
        </stf:imagen>
    </stf:informacionSalida>
</stf:sistemaTF>
