=== m-amaris/PIAT-JavaCC/[02] PIAT/Laboratorio/Practica 1/fase2/sistemaTransmision.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- SISTEMA-TRANSMISION-MIGUEL-AMARÃS -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.piat.upm.es/sistemaTransmision" 
xmlns:tns="http://www.piat.upm.es/sistemaTransmision" 
xmlns:mod="http://www.piat.upm.es/modulo" 
elementFormDefault="qualified">

    <xsd:import namespace="http://www.piat.upm.es/modulo" schemaLocation=".//modulo.xsd" />

    <xsd:element name="sistemaTx" type="tns:tipoSistemaTX" />

    <xsd:complexType name="tipoSistemaTX">
        <xsd:sequence minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="subsistemaTX" type="tns:tipoSubsistemaTX"  />
        </xsd:sequence>
        <xsd:attribute name="idSistemaTX" type="tns:tipoIdSistemaTX" use="required" />
    </xsd:complexType>

    <xsd:simpleType name="tipoIdSistemaTX">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="TX[0-9]{3}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="tipoSubsistemaTX">
        <xsd:sequence>
            <xsd:element name="nombreSusbsistemaTX" type="tns:tipoNombreSusbsistemaTX"  />
            <xsd:element name="nubeInformatica" type="tns:tipoNubeInformatica" minOccurs="0"/>
            <xsd:element name="modulosTXpIntegrados" type="tns:tipoModulosTXpIntegrados" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="tipoNombreSusbsistemaTX">
        <xsd:union memberTypes="xsd:integer tns:tipoString" />
    </xsd:simpleType>

    <xsd:simpleType name="tipoString">
        <xsd:restriction base="xsd:string">
            <xsd:maxLength value="6" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="tipoNubeInformatica">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded"> 
            <xsd:choice>
                <xsd:element name="nombreCompleto" type="xsd:string" />
                <xsd:element name="acronimo" type="xsd:string" />
            </xsd:choice>
            <xsd:element name="uri" type="xsd:anyURI"  />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="tipoListaModulosTXpIntegrados">
        <xsd:list itemType="mod:tipoIdModulo" />
    </xsd:simpleType>

    <xsd:simpleType name="tipoModulosTXpIntegrados">
        <xsd:restriction base="tns:tipoListaModulosTXpIntegrados">
            <xsd:minLength value="1" />
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== m-amaris/PIAT-JavaCC/[02] PIAT/Laboratorio/Practica 1/fase2/sistemaTransmision.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- SISTEMA-TRANSMISION-MIGUEL-AMARÍS -->
<tx:sistemaTx
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:tx="http://www.piat.upm.es/sistemaTransmision" 
xmlns:mod="http://www.piat.upm.es/modulo"
xsi:schemaLocation="http://www.piat.upm.es/sistemaTransmision sistemaTransmision.xsd" 
idSistemaTX="TX001">

    <tx:subsistemaTX>
        <tx:nombreSusbsistemaTX>Susbs2</tx:nombreSusbsistemaTX>
        <tx:nubeInformatica>
            <tx:acronimo>ASD</tx:acronimo>
            <tx:uri>http://nubeinformatica1.com</tx:uri>
        </tx:nubeInformatica>
        <tx:modulosTXpIntegrados>
            MODt0001 MODt0002
        </tx:modulosTXpIntegrados>
    </tx:subsistemaTX>

    <tx:subsistemaTX>
        <tx:nombreSusbsistemaTX>Susbs2</tx:nombreSusbsistemaTX>
        <tx:modulosTXpIntegrados>
            MODt0003 MODt0004
        </tx:modulosTXpIntegrados>
    </tx:subsistemaTX>
    
</tx:sistemaTx>
