=== m-amaris/PIAT-JavaCC/[02] PIAT/Laboratorio/Practica 1/fase2/sistemaTransformacion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- SISTEMA-TRANSFORMACION-MIGUEL-AMARÍS -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.piat.upm.es/sistemaTransformacion" 
xmlns:tns="http://www.piat.upm.es/sistemaTransformacion" 
xmlns:mod="http://www.piat.upm.es/modulo" 
elementFormDefault="qualified">

    <xsd:import namespace="http://www.piat.upm.es/modulo" schemaLocation="./modulo.xsd" />

    <xsd:notation name="GIF" public="image/gif" system="paint.exe" />
    <xsd:notation name="JPEG" public="image/jpeg" system="paint.exe" />
    <xsd:notation name="PNG" public="image/png" system="paint.exe" />

    <xsd:element name="sistemaTF" type="tns:tipoSistemaTF" />

    <xsd:complexType name="tipoSistemaTF">
        <xsd:sequence>
            <xsd:element name="informacionEntrada" type="tns:tipoInformacionEntrada"  />
            <xsd:element name="informacionSalida" type="tns:tipoInformacionSalida" />
        </xsd:sequence>
        <xsd:attribute name="idSistemaTF" type="tns:tipoIdSistemaTF" use="required" />
    </xsd:complexType>

    <xsd:simpleType name="tipoIdSistemaTF">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="TF[0-9]{3}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="tipoInformacionEntrada">
        <xsd:sequence>
            <xsd:choice>
                <xsd:element name="valor" type="tns:tipoValor" />
                <xsd:element name="foto" type="tns:tipoFoto" />
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tipoValor">
        <xsd:sequence>
            <xsd:element name="parametro" type="mod:tipoParametro"  />
            <xsd:element name="medida" type="mod:tipoMedida"  />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tipoFoto">
        <xsd:all>
            <xsd:element name="distancia" type="xsd:decimal"  />
            <xsd:element name="centro">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="longitud" type="tns:tipoLongitud"  />
                        <xsd:element name="latitud" type="tns:tipoLatitud"  />
                        <xsd:element name="forma" type="tns:tipoForma" />
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:all>
    </xsd:complexType>

    <xsd:simpleType name="tipoLongitud">
        <xsd:restriction base="xsd:decimal">
            <xsd:minInclusive value="0" />
            <xsd:maxInclusive value="180" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="tipoLatitud">
        <xsd:restriction base="xsd:decimal">
            <xsd:minInclusive value="-90" />
            <xsd:maxInclusive value="90" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="tipoForma">
        <xsd:restriction base="xsd:token">
            <xsd:enumeration value="cuadrado" />
            <xsd:enumeration value="rectangulo" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="tipoInformacionSalida">
        <xsd:sequence>
            <xsd:choice >
                <xsd:element name="texto" type="tns:tipoTexto" />
                <xsd:element name="imagen" type="tns:tipoImagen" />
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tipoTexto">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="formato" type="xsd:token" use="required" />
                <xsd:attribute name="longitud" type="xsd:positiveInteger" use="required" />
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="tipoImagen">
        <xsd:sequence>
            <xsd:element name="dimensiones" type="tns:tipoDimensiones" />
            <xsd:element name="descripcion" type="xsd:string" minOccurs="0" />
            <xsd:element name="contenido" type="tns:tipoContenido"  />
        </xsd:sequence>
        <xsd:attribute name="idImagen" type="tns:tipoIdImagen" use="required" />
    </xsd:complexType>

    <xsd:simpleType name="tipoIdImagen">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="IMAG[0-9]{3}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="tipoDimensiones">
        <xsd:restriction base="tns:tipoLista">
            <xsd:length value="2" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="tipoLista">
        <xsd:list itemType="xsd:integer" />
    </xsd:simpleType>

    <xsd:complexType name="tipoContenido">
        <xsd:simpleContent>
            <xsd:extension base="xsd:base64Binary">
                <xsd:attribute name="formato" type="tns:tipoFormato" use="required" />
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:simpleType name="tipoFormato">
        <xsd:restriction base="xsd:token">
            <xsd:enumeration value="GIF" />
            <xsd:enumeration value="JPEG" />
            <xsd:enumeration value="PNG" />
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== m-amaris/PIAT-JavaCC/[02] PIAT/Laboratorio/Practica 1/fase2/sistemaTransformacion2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- SISTEMA-TRANSFORMACION-MIGUEL-AMARÍS -->
<tf:sistemaTF 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:tf="http://www.piat.upm.es/sistemaTransformacion" 
xmlns:mod="http://www.piat.upm.es/modulo"
xsi:schemaLocation="http://www.piat.upm.es/sistemaTransformacion sistemaTransformacion.xsd" 
idSistemaTF="TF002">

    <tf:informacionEntrada>
        <tf:valor>
            <tf:parametro>asdasd</tf:parametro>
            <tf:medida>
                <mod:valor>54</mod:valor>
                <mod:unidades>m^2</mod:unidades>
            </tf:medida>
        </tf:valor>
    </tf:informacionEntrada>

    <tf:informacionSalida>
       <tf:texto formato=".txt" longitud="8374">
       </tf:texto>
    </tf:informacionSalida>

</tf:sistemaTF>

=== m-amaris/PIAT-JavaCC/[02] PIAT/Laboratorio/Practica 1/fase2/sistemaTransformacion1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- SISTEMA-TRANSFORMACION-MIGUEL-AMARÍS -->
<tf:sistemaTF xmlns:tf="http://www.piat.upm.es/sistemaTransformacion" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.piat.upm.es/sistemaTransformacion sistemaTransformacion.xsd" 
idSistemaTF="TF001">

    <tf:informacionEntrada>
        <tf:foto>
            <tf:distancia>234</tf:distancia>
            <tf:centro>
                <tf:longitud>0</tf:longitud>
                <tf:latitud>0</tf:latitud>
                <tf:forma>cuadrado</tf:forma>
            </tf:centro>
        </tf:foto>
    </tf:informacionEntrada>

    <tf:informacionSalida>
        <tf:imagen idImagen="IMAG001">
            <tf:dimensiones>123 123</tf:dimensiones>
            <tf:contenido formato="PNG"></tf:contenido>
        </tf:imagen>
    </tf:informacionSalida>

</tf:sistemaTF>
